service: aws-ticketing
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

functions:
  starterFunction:
    handler: src/handler/greeterHandler.greeter
    events: 
      - http:
          path: hello-world
          method: get