org: ticketing
app: testapp
service: aws-ticketing
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

functions:
  starterFunction:
    handler: app/handlers/userHandler.greeter
    events:
      - http:
          path: hello-world
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
